### ISSUE TITLE
Download Adobe XD and complete tutorial project that appears on open

### ISSUE THREAD

**Issue by daneobyrd** [EGaDSAustin/EGaDS-website#3]
XD is free. When you first open the application Adobe will guide you towards a tutorial project that will go through the basics. Also download the .zip from below that includes the images used in the tutorial project.

- [ ] Ali
- [x] Courtney
- [x] Dane
- [ ] Elena
- [ ] Justin
- [x] Robert
- [x] Terry
- [ ] Zara

https://www.adobe.com/products/xd.html
https://www.adobe.com/go/xd_tutorial_images
https://www.adobe.com/go/xd_tutorial_video

**Comment by xirothehero** [comment]
- [ ] Ali
- [ ] Robert
- [ ] Courtney
- [ ] Dane
- [ ] Justin
